import React from "react";

/* ok */
export const padding = [
  {
    id: 1,
    isText: true,
    name: "p",
    values: [
      "p-0",
      "p-px",
      "p-0.5",
      "p-1",
      "p-1.5",
      "p-2",
      "p-2.5",
      "p-3",
      "p-3.5",
      "p-4",
      "p-5",
      "p-6",
      "p-7",
      "p-8",
      "p-9",
      "p-10",
      "p-11",
      "p-12",
      "p-14",
      "p-16",
      "p-20",
      "p-24",
      "p-28",
      "p-32",
      "p-36",
      "p-40",
      "p-44",
      "p-48",
      "p-52",
      "p-56",
      "p-60",
      "p-64",
      "p-72",
      "p-80",
      "p-96",
    ],
  },
  {
    id: 2,
    isText: true,
    name: "pl",
    values: [
      "pl-0",
      "pl-px",
      "pl-0.5",
      "pl-1",
      "pl-1.5",
      "pl-2",
      "pl-2.5",
      "pl-3",
      "pl-3.5",
      "pl-4",
      "pl-5",
      "pl-6",
      "pl-7",
      "pl-8",
      "pl-9",
      "pl-10",
      "pl-11",
      "pl-12",
      "pl-14",
      "pl-16",
      "pl-20",
      "pl-24",
      "pl-28",
      "pl-32",
      "pl-36",
      "pl-40",
      "pl-44",
      "pl-48",
      "pl-52",
      "pl-56",
      "pl-60",
      "pl-64",
      "pl-72",
      "pl-80",
      "pl-96",
    ],
  },
  {
    id: 3,
    isText: true,
    name: "pr",
    values: [
      "pr-0",
      "pr-px",
      "pr-0.5",
      "pr-1",
      "pr-1.5",
      "pr-2",
      "pr-2.5",
      "pr-3",
      "pr-3.5",
      "pr-4",
      "pr-5",
      "pr-6",
      "pr-7",
      "pr-8",
      "pr-9",
      "pr-10",
      "pr-11",
      "pr-12",
      "pr-14",
      "pr-16",
      "pr-20",
      "pr-24",
      "pr-28",
      "pr-32",
      "pr-36",
      "pr-40",
      "pr-44",
      "pr-48",
      "pr-52",
      "pr-56",
      "pr-60",
      "pr-64",
      "pr-72",
      "pr-80",
      "pr-96",
    ],
  },
  {
    id: 4,
    isText: true,
    name: "pt",
    values: [
      "pt-0",
      "pt-px",
      "pt-0.5",
      "pt-1",
      "pt-1.5",
      "pt-2",
      "pt-2.5",
      "pt-3",
      "pt-3.5",
      "pt-4",
      "pt-5",
      "pt-6",
      "pt-7",
      "pt-8",
      "pt-9",
      "pt-10",
      "pt-11",
      "pt-12",
      "pt-14",
      "pt-16",
      "pt-20",
      "pt-24",
      "pt-28",
      "pt-32",
      "pt-36",
      "pt-40",
      "pt-44",
      "pt-48",
      "pt-52",
      "pt-56",
      "pt-60",
      "pt-64",
      "pt-72",
      "pt-80",
      "pt-96",
    ],
  },
  {
    id: 5,
    isText: true,
    name: "pb",
    values: [
      "pb-0",
      "pb-px",
      "pb-0.5",
      "pb-1",
      "pb-1.5",
      "pb-2",
      "pb-2.5",
      "pb-3",
      "pb-3.5",
      "pb-4",
      "pb-5",
      "pb-6",
      "pb-7",
      "pb-8",
      "pb-9",
      "pb-10",
      "pb-11",
      "pb-12",
      "pb-14",
      "pb-16",
      "pb-20",
      "pb-24",
      "pb-28",
      "pb-32",
      "pb-36",
      "pb-40",
      "pb-44",
      "pb-48",
      "pb-52",
      "pb-56",
      "pb-60",
      "pb-64",
      "pb-72",
      "pb-80",
      "pb-96",
    ],
  },
  {
    id: 6,
    isText: true,
    name: "px",
    values: [
      "px-0",
      "px-px",
      "px-0.5",
      "px-1",
      "px-1.5",
      "px-2",
      "px-2.5",
      "px-3",
      "px-3.5",
      "px-4",
      "px-5",
      "px-6",
      "px-7",
      "px-8",
      "px-9",
      "px-10",
      "px-11",
      "px-12",
      "px-14",
      "px-16",
      "px-20",
      "px-24",
      "px-28",
      "px-32",
      "px-36",
      "px-40",
      "px-44",
      "px-48",
      "px-52",
      "px-56",
      "px-60",
      "px-64",
      "px-72",
      "px-80",
      "px-96",
    ],
  },
  {
    id: 7,
    isText: true,
    name: "py",
    values: [
      "py-0",
      "py-px",
      "py-0.5",
      "py-1",
      "py-1.5",
      "py-2",
      "py-2.5",
      "py-3",
      "py-3.5",
      "py-4",
      "py-5",
      "py-6",
      "py-7",
      "py-8",
      "py-9",
      "py-10",
      "py-11",
      "py-12",
      "py-14",
      "py-16",
      "py-20",
      "py-24",
      "py-28",
      "py-32",
      "py-36",
      "py-40",
      "py-44",
      "py-48",
      "py-52",
      "py-56",
      "py-60",
      "py-64",
      "py-72",
      "py-80",
      "py-96",
    ],
  },
];

/* ok */
export const margin = [
  {
    id: 1,
    isText: true,
    name: "m",
    values: [
      "m-0",
      "m-px",
      "m-0.5",
      "m-1",
      "m-1.5",
      "m-2",
      "m-2.5",
      "m-3",
      "m-3.5",
      "m-4",
      "m-5",
      "m-6",
      "m-7",
      "m-8",
      "m-9",
      "m-10",
      "m-11",
      "m-12",
      "m-14",
      "m-16",
      "m-20",
      "m-24",
      "m-28",
      "m-32",
      "m-36",
      "m-40",
      "m-44",
      "m-48",
      "m-52",
      "m-56",
      "m-60",
      "m-64",
      "m-72",
      "m-80",
      "m-96",
    ],
  },
  {
    id: 2,
    isText: true,
    name: "ml",
    values: [
      "ml-0",
      "ml-px",
      "ml-0.5",
      "ml-1",
      "ml-1.5",
      "ml-2",
      "ml-2.5",
      "ml-3",
      "ml-3.5",
      "ml-4",
      "ml-5",
      "ml-6",
      "ml-7",
      "ml-8",
      "ml-9",
      "ml-10",
      "ml-11",
      "ml-12",
      "ml-14",
      "ml-16",
      "ml-20",
      "ml-24",
      "ml-28",
      "ml-32",
      "ml-36",
      "ml-40",
      "ml-44",
      "ml-48",
      "ml-52",
      "ml-56",
      "ml-60",
      "ml-64",
      "ml-72",
      "ml-80",
      "ml-96",
    ],
  },
  {
    id: 3,
    isText: true,
    name: "mr",
    values: [
      "mr-0",
      "mr-px",
      "mr-0.5",
      "mr-1",
      "mr-1.5",
      "mr-2",
      "mr-2.5",
      "mr-3",
      "mr-3.5",
      "mr-4",
      "mr-5",
      "mr-6",
      "mr-7",
      "mr-8",
      "mr-9",
      "mr-10",
      "mr-11",
      "mr-12",
      "mr-14",
      "mr-16",
      "mr-20",
      "mr-24",
      "mr-28",
      "mr-32",
      "mr-36",
      "mr-40",
      "mr-44",
      "mr-48",
      "mr-52",
      "mr-56",
      "mr-60",
      "mr-64",
      "mr-72",
      "mr-80",
      "mr-96",
    ],
  },
  {
    id: 4,
    isText: true,
    name: "mt",
    values: [
      "mt-0",
      "mt-px",
      "mt-0.5",
      "mt-1",
      "mt-1.5",
      "mt-2",
      "mt-2.5",
      "mt-3",
      "mt-3.5",
      "mt-4",
      "mt-5",
      "mt-6",
      "mt-7",
      "mt-8",
      "mt-9",
      "mt-10",
      "mt-11",
      "mt-12",
      "mt-14",
      "mt-16",
      "mt-20",
      "mt-24",
      "mt-28",
      "mt-32",
      "mt-36",
      "mt-40",
      "mt-44",
      "mt-48",
      "mt-52",
      "mt-56",
      "mt-60",
      "mt-64",
      "mt-72",
      "mt-80",
      "mt-96",
    ],
  },
  {
    id: 5,
    isText: true,
    name: "mb",
    values: [
      "mb-0",
      "mb-px",
      "mb-0.5",
      "mb-1",
      "mb-1.5",
      "mb-2",
      "mb-2.5",
      "mb-3",
      "mb-3.5",
      "mb-4",
      "mb-5",
      "mb-6",
      "mb-7",
      "mb-8",
      "mb-9",
      "mb-10",
      "mb-11",
      "mb-12",
      "mb-14",
      "mb-16",
      "mb-20",
      "mb-24",
      "mb-28",
      "mb-32",
      "mb-36",
      "mb-40",
      "mb-44",
      "mb-48",
      "mb-52",
      "mb-56",
      "mb-60",
      "mb-64",
      "mb-72",
      "mb-80",
      "mb-96",
    ],
  },
  {
    id: 6,
    isText: true,
    name: "mx",
    values: [
      "mx-0",
      "m-px",
      "mx-0.5",
      "mx-1",
      "mx-1.5",
      "mx-2",
      "mx-2.5",
      "mx-3",
      "mx-3.5",
      "mx-4",
      "mx-5",
      "mx-6",
      "mx-7",
      "mx-8",
      "mx-9",
      "mx-10",
      "mx-11",
      "mx-12",
      "mx-14",
      "mx-16",
      "mx-20",
      "mx-24",
      "mx-28",
      "mx-32",
      "mx-36",
      "mx-40",
      "mx-44",
      "mx-48",
      "mx-52",
      "mx-56",
      "mx-60",
      "mx-64",
      "mx-72",
      "mx-80",
      "mx-96",
    ],
  },
  {
    id: 7,
    isText: true,
    name: "my",
    values: [
      "my-0",
      "my-px",
      "my-0.5",
      "my-1",
      "my-1.5",
      "my-2",
      "my-2.5",
      "my-3",
      "my-3.5",
      "my-4",
      "my-5",
      "my-6",
      "my-7",
      "my-8",
      "my-9",
      "my-10",
      "my-11",
      "my-12",
      "my-14",
      "my-16",
      "my-20",
      "my-24",
      "my-28",
      "my-32",
      "my-36",
      "my-40",
      "my-44",
      "my-48",
      "my-52",
      "my-56",
      "my-60",
      "my-64",
      "my-72",
      "my-80",
      "my-96",
    ],
  },
];

/* ok */
export const spacing = [
  {
    id: 1,
    isText: true,
    name: "space-x",
    values: [
      "space-x-0",
      "space-x-1",
      "space-x-2",
      "space-x-3",
      "space-x-4",
      "space-x-5",
      "space-x-6",
      "space-x-7",
      "space-x-8",
      "space-x-9",
      "space-x-10",
      "space-x-11",
      "space-x-12",
      "space-x-14",
      "space-x-16",
      "space-x-20",
      "space-x-24",
      "space-x-28",
      "space-x-32",
      "space-x-36",
      "space-x-40",
      "space-x-44",
      "space-x-48",
      "space-x-52",
      "space-x-56",
      "space-x-60",
      "space-x-64",
      "space-x-72",
      "space-x-80",
      "space-x-96",
      "space-x-0.5",
      "space-x-1.5",
      "space-x-2.5",
      "space-x-3.5",
      "space-x-reverse",
      "space-x-px",
    ],
  },
  {
    id: 2,
    isText: true,
    name: "space-y",
    values: [
      "space-y-0",
      "space-y-1",
      "space-y-2",
      "space-y-3",
      "space-y-4",
      "space-y-5",
      "space-y-6",
      "space-y-7",
      "space-y-8",
      "space-y-9",
      "space-y-10",
      "space-y-11",
      "space-y-12",
      "space-y-14",
      "space-y-16",
      "space-y-20",
      "space-y-24",
      "space-y-28",
      "space-y-32",
      "space-y-36",
      "space-y-40",
      "space-y-44",
      "space-y-48",
      "space-y-52",
      "space-y-56",
      "space-y-60",
      "space-y-64",
      "space-y-72",
      "space-y-80",
      "space-y-96",
      "space-y-0.5",
      "space-y-1.5",
      "space-y-2.5",
      "space-y-3.5",
      "space-y-reverse",
      "space-y-px",
    ],
  } /* per px e reverse? */,
];

/* ok */
export const flex = [
  {
    id: 1,
    isText: true,
    name: "flex-basis",
    values: [
      "basis-0",
      "basis-1",
      "basis-2",
      "basis-3",
      "basis-4",
      "basis-5",
      "basis-6",
      "basis-7",
      "basis-8",
      "basis-9",
      "basis-10",
      "basis-11",
      "basis-12",
      "basis-14",
      "basis-16",
      "basis-20",
      "basis-24",
      "basis-28",
      "basis-32",
      "basis-36",
      "basis-40",
      "basis-44",
      "basis-48",
      "basis-52",
      "basis-56",
      "basis-60",
      "basis-64",
      "basis-72",
      "basis-80",
      "basis-96",
      "basis-auto",
      "basis-px",
      "basis-0.5",
      "basis-1.5",
      "basis-2.5",
      "basis-3.5",
      "basis-1/2",
      "basis-1/3",
      "basis-2/3",
      "basis-1/4",
      "basis-2/4",
      "basis-3/4",
      "basis-1/5",
      "basis-2/5",
      "basis-3/5",
      "basis-4/5",
      "basis-1/6",
      "basis-2/6",
      "basis-3/6",
      "basis-4/6",
      "basis-5/6",
      "basis-1/12",
      "basis-2/12",
      "basis-3/12",
      "basis-4/12",
      "basis-5/12",
      "basis-6/12",
      "basis-7/12",
      "basis-8/12",
      "basis-9/12",
      "basis-10/12",
      "basis-11/12",
      "basis-full",
    ],
  } /* auto,px, full? */,
  {
    id: 2,
    isText: false,
    name: "flex-direction",
    values: ["flex-row", "flex-row-reverse", "flex-col", "flex-col-reverse"],
  },
  {
    id: 3,
    isText: false,
    name: "flex-wrap",
    values: ["flex-wrap", "flex-wrap-reverse", "flex-nowrap"],
  },
  {
    id: 4,
    isText: false,
    name: "flex",
    values: ["flex-1", "flex-auto", "flex-initial", "flex-none"],
  },
  { id: 5, isText: false, name: "grow", values: ["grow-0", "grow"] },
  { id: 6, isText: false, name: "flex-shrink", values: ["shrink-0", "shrink"] },

  /* gap */
  {
    id: 7,
    isText: true,
    name: "gap",
    values: [
      "gap-0",
      "gap-px",
      "gap-0.5",
      "gap-1",
      "gap-1.5",
      "gap-2",
      "gap-2.5",
      "gap-3",
      "gap-3.5",
      "gap-4",
      "gap-5",
      "gap-6",
      "gap-7",
      "gap-8",
      "gap-9",
      "gap-10",
      "gap-11",
      "gap-12",
      "gap-14",
      "gap-16",
      "gap-20",
      "gap-24",
      "gap-28",
      "gap-32",
      "gap-36",
      "gap-40",
      "gap-44",
      "gap-48",
      "gap-52",
      "gap-56",
      "gap-60",
      "gap-64",
      "gap-72",
      "gap-80",
      "gap-96",
    ],
  },
  {
    id: 8,
    isText: true,
    name: "gap-x",
    values: [
      "gap-x-0",
      "gap-x-px",
      "gap-x-0.5",
      "gap-x-1",
      "gap-x-1.5",
      "gap-x-2",
      "gap-x-2.5",
      "gap-x-3",
      "gap-x-3.5",
      "gap-x-4",
      "gap-x-5",
      "gap-x-6",
      "gap-x-7",
      "gap-x-8",
      "gap-x-9",
      "gap-x-10",
      "gap-x-11",
      "gap-x-12",
      "gap-x-14",
      "gap-x-16",
      "gap-x-20",
      "gap-x-24",
      "gap-x-28",
      "gap-x-32",
      "gap-x-36",
      "gap-x-40",
      "gap-x-44",
      "gap-x-48",
      "gap-x-52",
      "gap-x-56",
      "gap-x-60",
      "gap-x-64",
      "gap-x-72",
      "gap-x-80",
      "gap-x-96",
    ],
  },
  {
    id: 9,
    isText: true,
    name: "gap-y",
    values: [
      "gap-y-0",
      "gap-y-px",
      "gap-y-0.5",
      "gap-y-1",
      "gap-y-1.5",
      "gap-y-2",
      "gap-y-2.5",
      "gap-y-3",
      "gap-y-3.5",
      "gap-y-4",
      "gap-y-5",
      "gap-y-6",
      "gap-y-7",
      "gap-y-8",
      "gap-y-9",
      "gap-y-10",
      "gap-y-11",
      "gap-y-12",
      "gap-y-14",
      "gap-y-16",
      "gap-y-20",
      "gap-y-24",
      "gap-y-28",
      "gap-y-32",
      "gap-y-36",
      "gap-y-40",
      "gap-y-44",
      "gap-y-48",
      "gap-y-52",
      "gap-y-56",
      "gap-y-60",
      "gap-y-64",
      "gap-y-72",
      "gap-y-80",
      "gap-y-96",
    ],
  },

  /* order (flex) */
  {
    id: 10,
    isText: false,
    name: "order",
    values: [
      "order-0",
      "order-1",
      "order-2",
      "order-3",
      "order-4",
      "order-5",
      "order-6",
      "order-7",
      "order-8",
      "order-9",
      "order-10",
      "order-11",
      "order-12",
      "order-first",
      "order-last",
      "order-none",
    ],
  },

  /* justify content */
  {
    id: 11,
    isText: false,
    name: "justify-content",
    values: [
      "justify-start",
      "justify-end",
      "justify-center",
      "justify-between",
      "justify-around",
      "justify-evenly",
    ],
  },
  {
    id: 12,
    isText: false,
    name: "justify-items",
    values: [
      "justify-items-start",
      "justify-items-end",
      "justify-items-center",
      "justify-items-stretch",
    ],
  },
  {
    id: 13,
    isText: false,
    name: "justify-self",
    values: [
      "justify-self-auto",
      "justify-self-start",
      "justify-self-end",
      "justify-self-center",
      "justify-self-stretch",
    ],
  },

  /* align content */
  {
    id: 14,
    isText: false,
    name: "align-content",
    values: [
      "content-center",
      "content-start",
      "content-end",
      "content-between",
      "content-around",
      "content-evenly",
    ],
  },
  {
    id: 15,
    isText: false,
    name: "align-items",
    values: [
      "items-center",
      "items-start",
      "items-end",
      "items-baseline",
      "items-stretch",
    ],
  },
  {
    id: 16,
    isText: false,
    name: "align-self",
    values: [
      "self-auto",
      "self-center",
      "self-start",
      "self-end",
      "self-baseline",
      "self-stretch",
    ],
  },

  /* place content */
  {
    id: 17,
    isText: false,
    name: "place-content",
    values: [
      "place-content-center",
      "place-content-start",
      "place-content-end",
      "place-content-between",
      "place-content-around",
      "place-content-evenly",
      "place-content-stretch",
    ],
  },
  {
    id: 18,
    isText: false,
    name: "place-items",
    values: [
      "place-items-start",
      "place-items-end",
      "place-items-center",
      "place-items-stretch",
    ],
  },
  {
    id: 19,
    isText: false,
    name: "place-self",
    values: [
      "place-self-auto",
      "place-self-start",
      "place-self-end",
      "place-self-center",
      "place-self-stretch",
    ],
  },
];

/* ok continuare ad aggiunger     isText: false, ...  */
export const grid = [
  {
    id: 1,
    name: "grid-template-columns",
    values: [
      "grid-cols-1",
      "grid-cols-2",
      "grid-cols-3",
      "grid-cols-4",
      "grid-cols-5",
      "grid-cols-6",
      "grid-cols-7",
      "grid-cols-8",
      "grid-cols-9",
      "grid-cols-10",
      "grid-cols-11",
      "grid-cols-12",
      "grid-cols-none",
    ],
  } /* columns */,
  {
    id: 2,
    name: "grid-column-span",
    values: [
      "col-auto",
      "col-span-1",
      "col-span-2",
      "col-span-3",
      "col-span-4",
      "col-span-5",
      "col-span-6",
      "col-span-7",
      "col-span-8",
      "col-span-9",
      "col-span-10",
      "col-span-11",
      "col-span-12",
      "col-span-full",
    ],
  },
  {
    id: 3,
    name: "grid-column-start",
    values: [
      "col-start-1",
      "col-start-2",
      "col-start-3",
      "col-start-4",
      "col-start-5",
      "col-start-6",
      "col-start-7",
      "col-start-8",
      "col-start-9",
      "col-start-10",
      "col-start-11",
      "col-start-12",
      "col-start-13",
      "col-start-auto",
    ],
  },
  {
    id: 4,
    name: "grid-column-end",
    values: [
      "col-end-1",
      "col-end-2",
      "col-end-3",
      "col-end-4",
      "col-end-5",
      "col-end-6",
      "col-end-7",
      "col-end-8",
      "col-end-9",
      "col-end-10",
      "col-end-11",
      "col-end-12",
      "col-end-13",
      "col-end-auto",
    ],
  },

  {
    id: 6,
    name: "grid-template-rows",
    values: [
      "grid-rows-1",
      "grid-rows-2",
      "grid-rows-3",
      "grid-rows-4",
      "grid-rows-5",
      "grid-rows-6",
      "grid-rows-none",
    ],
  } /* rows */,
  {
    id: 7,
    name: "grid-row-span",
    values: [
      "row-auto",
      "row-span-1",
      "row-span-2",
      "row-span-3",
      "row-span-4",
      "row-span-5",
      "row-span-6",
      "row-span-full",
    ],
  } /* Grid Row Start/End */,
  {
    id: 9,
    name: "grid-row-start",
    values: [
      "row-start-auto",
      "row-start-1",
      "row-start-2",
      "row-start-3",
      "row-start-4",
      "row-start-5",
      "row-start-6",
      "row-start-7",
      "row-start-full",
    ],
  },
  {
    id: 10,
    name: "grid-row-end",
    values: [
      "row-end-auto",
      "row-end-1",
      "row-end-2",
      "row-end-3",
      "row-end-4",
      "row-end-5",
      "row-end-6",
      "row-end-7",
      "row-end-full",
    ],
  },

  {
    id: 11,
    name: "grid-auto-flow",
    values: [
      "grid-flow-row",
      "grid-flow-col",
      "grid-flow-row-dense",
      "grid-flow-col-dense",
    ],
  },
  {
    id: 12,
    name: "grid-auto-columns",
    values: [
      "auto-cols-auto",
      "auto-cols-min",
      "auto-cols-max",
      "auto-cols-fr",
    ],
  },
  {
    id: 13,
    name: "grid-auto-rows",
    values: [
      "auto-rows-auto",
      "auto-rows-min",
      "auto-rows-max",
      "auto-rows-fr",
    ],
  },

  /* gap */
  {
    id: 14,
    name: "gap",
    values: [
      "gap-0",
      "gap-px",
      "gap-0.5",
      "gap-1",
      "gap-1.5",
      "gap-2",
      "gap-2.5",
      "gap-3",
      "gap-3.5",
      "gap-4",
      "gap-5",
      "gap-6",
      "gap-7",
      "gap-8",
      "gap-9",
      "gap-10",
      "gap-11",
      "gap-12",
      "gap-14",
      "gap-16",
      "gap-20",
      "gap-24",
      "gap-28",
      "gap-32",
      "gap-36",
      "gap-40",
      "gap-44",
      "gap-48",
      "gap-52",
      "gap-56",
      "gap-60",
      "gap-64",
      "gap-72",
      "gap-80",
      "gap-96",
    ],
  },
  {
    id: 15,
    name: "gap-x",
    values: [
      "gap-x-0",
      "gap-x-px",
      "gap-x-0.5",
      "gap-x-1",
      "gap-x-1.5",
      "gap-x-2",
      "gap-x-2.5",
      "gap-x-3",
      "gap-x-3.5",
      "gap-x-4",
      "gap-x-5",
      "gap-x-6",
      "gap-x-7",
      "gap-x-8",
      "gap-x-9",
      "gap-x-10",
      "gap-x-11",
      "gap-x-12",
      "gap-x-14",
      "gap-x-16",
      "gap-x-20",
      "gap-x-24",
      "gap-x-28",
      "gap-x-32",
      "gap-x-36",
      "gap-x-40",
      "gap-x-44",
      "gap-x-48",
      "gap-x-52",
      "gap-x-56",
      "gap-x-60",
      "gap-x-64",
      "gap-x-72",
      "gap-x-80",
      "gap-x-96",
    ],
  },
  {
    id: 16,
    name: "gap-y",
    values: [
      "gap-y-0",
      "gap-y-px",
      "gap-y-0.5",
      "gap-y-1",
      "gap-y-1.5",
      "gap-y-2",
      "gap-y-2.5",
      "gap-y-3",
      "gap-y-3.5",
      "gap-y-4",
      "gap-y-5",
      "gap-y-6",
      "gap-y-7",
      "gap-y-8",
      "gap-y-9",
      "gap-y-10",
      "gap-y-11",
      "gap-y-12",
      "gap-y-14",
      "gap-y-16",
      "gap-y-20",
      "gap-y-24",
      "gap-y-28",
      "gap-y-32",
      "gap-y-36",
      "gap-y-40",
      "gap-y-44",
      "gap-y-48",
      "gap-y-52",
      "gap-y-56",
      "gap-y-60",
      "gap-y-64",
      "gap-y-72",
      "gap-y-80",
      "gap-y-96",
    ],
  },

  /* order (grid) */
  {
    id: 17,
    name: "order",
    values: [
      "order-0",
      "order-1",
      "order-2",
      "order-3",
      "order-4",
      "order-5",
      "order-6",
      "order-7",
      "order-8",
      "order-9",
      "order-10",
      "order-11",
      "order-12",
      "order-first",
      "order-last",
      "order-none",
    ],
  },

  /* justify content */
  {
    id: 19,
    name: "justify-content",
    values: [
      "justify-start",
      "justify-end",
      "justify-center",
      "justify-between",
      "justify-around",
      "justify-evenly",
    ],
  },
  {
    id: 20,
    name: "justify-items",
    values: [
      "justify-items-start",
      "justify-items-end",
      "justify-items-center",
      "justify-items-stretch",
    ],
  },
  {
    id: 21,
    name: "justify-self",
    values: [
      "justify-self-auto",
      "justify-self-start",
      "justify-self-end",
      "justify-self-center",
      "justify-self-stretch",
    ],
  },

  /* align content */
  {
    id: 22,
    name: "align-content",
    values: [
      "content-center",
      "content-start",
      "content-end",
      "content-between",
      "content-around",
      "content-evenly",
    ],
  },
  {
    id: 23,
    name: "align-items",
    values: [
      "items-center",
      "items-start",
      "items-end",
      "items-baseline",
      "items-stretch",
    ],
  },
  {
    id: 24,
    name: "align-self",
    values: [
      "self-auto",
      "self-center",
      "self-start",
      "self-end",
      "self-baseline",
      "self-stretch",
    ],
  },

  /* place content */
  {
    id: 25,
    name: "place-content",
    values: [
      "place-content-center",
      "place-content-start",
      "place-content-end",
      "place-content-between",
      "place-content-around",
      "place-content-evenly",
      "place-content-stretch",
    ],
  },
  {
    id: 26,
    name: "place-items",
    values: [
      "place-items-start",
      "place-items-end",
      "place-items-center",
      "place-items-stretch",
    ],
  },
  {
    id: 27,
    name: "place-self",
    values: [
      "place-self-auto",
      "place-self-start",
      "place-self-end",
      "place-self-center",
      "place-self-stretch",
    ],
  },
];

/* ok */
export const layout = [
  /* Layout (+ Typography + Backgrounds + Borders) */
  {
    id: 1,
    name: "aspect-ratio",
    values: ["aspect-auto", "aspect-square", "aspect-video"],
  },
  { id: 2, name: "container", values: ["container"] },
  {
    id: 3,
    name: "columns",
    values: [
      "columns-1",
      "columns-2",
      "columns-3",
      "columns-4",
      "columns-5",
      "columns-6",
      "columns-7",
      "columns-8",
      "columns-9",
      "columns-10",
      "columns-11",
      "columns-12",
      "columns-auto",
      "columns-3xs",
      "columns-2xs",
      "columns-xs",
      "columns-sm",
      "columns-md",
      "columns-lg",
      "columns-xl",
      "columns-2xl",
      "columns-3xl",
      "columns-4xl",
      "columns-5xl",
      "columns-6xl",
      "columns-7xl",
    ],
  },
  {
    id: 4,
    name: "break-after",
    values: [
      "break-after-auto",
      "break-after-avoid",
      "break-after-all",
      "break-after-avoid-page",
      "break-after-page",
      "break-after-left",
      "break-after-right",
      "break-after-column",
    ],
  },
  {
    id: 5,
    name: "break-before",
    values: [
      "break-before-auto",
      "break-before-avoid",
      "break-before-all",
      "break-before-avoid-page",
      "break-before-page",
      "break-before-left",
      "break-before-right",
      "break-before-column",
    ],
  },
  {
    id: 6,
    name: "break-inside",
    values: [
      "break-inside-auto",
      "break-inside-avoid",
      "break-inside-avoid-page",
      "break-inside-avoid-column",
    ],
  },
  {
    id: 7,
    name: "box-decoration-break",
    values: ["box-decoration-clone", "box-decoration-slice"],
  },
  { id: 8, name: "box-sizing", values: ["box-border", "box-content"] },
  {
    id: 9,
    name: "display",
    values: [
      "block",
      "inline-block",
      "inline",
      "flex",
      "inline-flex",
      "table",
      "inline-table",
      "table-caption",
      "table-cell",
      "table-column",
      "table-column-group",
      "table-footer-group",
      "table-header-group",
      "table-row-group",
      "table-row",
      "flow-root",
      "grid",
      "inline-grid",
      "contents",
      "list-item",
      "hidden",
    ],
  },
  {
    id: 10,
    name: "float",
    values: ["float-right", "float-left", "float-none"],
  },
  {
    id: 11,
    name: "clear",
    values: ["clear-right", "clear-left", "clear-none", "clear-both"],
  },
  { id: 12, name: "isolation", values: ["isolate", "isolate-none"] },
  {
    id: 13,
    ame: "object-fit",
    values: [
      "object-contain",
      "object-cover",
      "object-fill",
      "object-none",
      "object-scale-down",
    ],
  },
  {
    id: 14,
    ame: "object-position",
    values: [
      "object-bottom",
      "object-center",
      "object-left",
      "object-left-bottom",
      "object-right",
      "object-right-bottom",
      "object-right-top",
      "object-top",
    ],
  },
  {
    id: 15,
    name: "overflow",
    values: [
      "overflow-auto",
      "overflow-hidden",
      "overflow-clip",
      "overflow-visible",
      "overflow-scroll",
      "overflow-x-auto",
      "overflow-y-auto",
      "overflow-x-hidden",
      "overflow-y-hidden",
      "overflow-x-clip",
      "overflow-y-clip",
      "overflow-x-visible",
      "overflow-y-visible",
      "overflow-x-scroll",
      "overflow-y-scroll",
    ],
  },
  {
    id: 16,
    name: "overscroll-behavior",
    values: [
      "overscroll-auto",
      "overscroll-contain",
      "overscroll-none",
      "overscroll-y-auto",
      "overscroll-y-contain",
      "overscroll-y-none",
      "overscroll-x-auto",
      "overscroll-x-contain",
      "overscroll-x-none",
    ],
  },
  {
    id: 17,
    name: "position",
    values: ["static", "fixed", "absolute", "relative", "sticky"],
  },
  {
    id: 18,
    name: "inset",
    values: [
      "inset-0",
      "inset-x-0",
      "inset-y-0",
      "top-0",
      "right-0",
      "bottom-0",
      "left-0",
      "inset-px",
      "inset-x-px",
      "inset-y-px",
      "top-px",
      "right-px",
      "bottom-px",
      "left-px",
      "inset-0.5",
      "inset-x-0.5",
      "inset-y-0.5",
      "top-0.5",
      "right-0.5",
      "bottom-0.5",
      "left-0.5",
      "inset-1",
      "inset-x-1",
      "inset-y-1",
      "top-1",
      "right-1",
      "bottom-1",
      "left-1",
      "inset-1.5",
      "inset-x-1.5",
      "inset-y-1.5",
      "top-1.5",
      "right-1.5",
      "bottom-1.5",
      "left-1.5",
      "inset-2",
      "inset-x-2",
      "inset-y-2",
      "top-2",
      "right-2",
      "bottom-2",
      "left-2",
      "inset-2.5",
      "inset-x-2.5",
      "inset-y-2.5",
      "top-2.5",
      "right-2.5",
      "bottom-2.5",
      "left-2.5",
      "inset-3",
      "inset-x-3",
      "inset-y-3",
      "top-3",
      "right-3",
      "bottom-3",
      "left-3",
      "inset-3.5",
      "inset-x-3.5",
      "inset-y-3.5",
      "top-3.5",
      "right-3.5",
      "bottom-3.5",
      "left-3.5",
      "inset-4",
      "inset-x-4",
      "inset-y-4",
      "top-4",
      "right-4",
      "bottom-4",
      "left-4",
      "inset-5",
      "inset-x-5",
      "inset-y-5",
      "top-5",
      "right-5",
      "bottom-5",
      "left-5",
      "inset-6",
      "inset-x-6",
      "inset-y-6",
      "top-6",
      "right-6",
      "bottom-6",
      "left-6",
      "inset-7",
      "inset-x-7",
      "inset-y-7",
      "top-7",
      "right-7",
      "bottom-7",
      "left-7",
      "inset-8",
      "inset-x-8",
      "inset-y-8",
      "top-8",
      "right-8",
      "bottom-8",
      "left-8",
      "inset-9",
      "inset-x-9",
      "inset-y-9",
      "top-9",
      "right-9",
      "bottom-9",
      "left-9",
      "inset-10",
      "inset-x-10",
      "inset-y-10",
      "top-10",
      "right-10",
      "bottom-10",
      "left-10",
      "inset-11",
      "inset-x-11",
      "inset-y-11",
      "top-11",
      "right-11",
      "bottom-11",
      "left-11",
      "inset-12",
      "inset-x-12",
      "inset-y-12",
      "top-12",
      "right-12",
      "bottom-12",
      "left-12",
      "inset-14",
      "inset-x-14",
      "inset-y-14",
      "top-14",
      "right-14",
      "bottom-14",
      "left-14",
      "inset-16",
      "inset-x-16",
      "inset-y-16",
      "top-16",
      "right-16",
      "bottom-16",
      "left-16",
      "inset-20",
      "inset-x-20",
      "inset-y-20",
      "top-20",
      "right-20",
      "bottom-20",
      "left-20",
      "inset-24",
      "inset-x-24",
      "inset-y-24",
      "top-24",
      "right-24",
      "bottom-24",
      "left-24",
      "inset-28",
      "inset-x-28",
      "inset-y-28",
      "top-28",
      "right-28",
      "bottom-28",
      "left-28",
      "inset-32",
      "inset-x-32",
      "inset-y-32",
      "top-32",
      "right-32",
      "bottom-32",
      "left-32",
      "inset-36",
      "inset-x-36",
      "inset-y-36",
      "top-36",
      "right-36",
      "bottom-36",
      "left-36",
      "inset-40",
      "inset-x-40",
      "inset-y-40",
      "top-40",
      "right-40",
      "bottom-40",
      "left-40",
      "inset-44",
      "inset-x-44",
      "inset-y-44",
      "top-44",
      "right-44",
      "bottom-44",
      "left-44",
      "inset-48",
      "inset-x-48",
      "inset-y-48",
      "top-48",
      "right-48",
      "bottom-48",
      "left-48",
      "inset-52",
      "inset-x-52",
      "inset-y-52",
      "top-52",
      "right-52",
      "bottom-52",
      "left-52",
      "inset-56",
      "inset-x-56",
      "inset-y-56",
      "top-56",
      "right-56",
      "bottom-56",
      "left-56",
      "inset-60",
      "inset-x-60",
      "inset-y-60",
      "top-60",
      "right-60",
      "bottom-60",
      "left-60",
      "inset-64",
      "inset-x-64",
      "inset-y-64",
      "top-64",
      "right-64",
      "bottom-64",
      "left-64",
      "inset-72",
      "inset-x-72",
      "inset-y-72",
      "top-72",
      "right-72",
      "bottom-72",
      "left-72",
      "inset-80",
      "inset-x-80",
      "inset-y-80",
      "top-80",
      "right-80",
      "bottom-80",
      "left-80",
      "inset-96",
      "inset-x-96",
      "inset-y-96",
      "top-96",
      "right-96",
      "bottom-96",
      "left-96",

      "inset-full",
      "inset-x-full",
      "inset-y-full",
      "top-full",
      "right-full",
      "bottom-full",
      "left-full",
      "inset-auto",
      "inset-x-auto",
      "inset-y-auto",
      "top-auto",
      "right-auto",
      "bottom-auto",
      "left-auto",
      "inset-1/2",
      "inset-x-1/2",
      "inset-y-1/2",
      "top-1/2",
      "right-1/2",
      "bottom-1/2",
      "left-1/2",
      "inset-1/3",
      "inset-x-1/3",
      "inset-y-1/3",
      "top-1/3",
      "right-1/3",
      "bottom-1/3",
      "left-1/3",
      "inset-2/3",
      "inset-x-2/3",
      "inset-y-2/3",
      "top-2/3",
      "right-2/3",
      "bottom-2/3",
      "left-2/3",
      "inset-1/4",
      "inset-x-1/4",
      "inset-y-1/4",
      "top-1/4",
      "right-1/4",
      "bottom-1/4",
      "left-1/4",
      "inset-2/4",
      "inset-x-2/4",
      "inset-y-2/4",
      "top-2/4",
      "right-2/4",
      "bottom-2/4",
      "left-2/4",
      "inset-3/4",
      "inset-x-3/4",
      "inset-y-3/4",
      "top-3/4",
      "right-3/4",
      "bottom-3/4",
      "left-3/4",
    ],
  },
  { id: 19, name: "visibility", values: ["visible", "invisible"] },
  {
    id: 20,
    name: "z-index",
    values: ["z-0", "z-10", "z-20", "z-30", "z-40", "z-50", "z-auto"],
  },
];

/* ok */
export const typography = [
  /* Text / Font */
  {
    id: 1,
    name: "font-family",
    values: ["font-sans", "font-serif", "font-mono"],
  },
  {
    id: 2,
    name: "font-size",
    values: [
      "text-xs",
      "text-sm",
      "text-base",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "text-6xl",
      "text-7xl",
      "text-8xl",
      "text-9xl",
    ],
  },
  {
    id: 3,
    name: "font-smoothing",
    values: ["antialiased", "subpixel-antialiased"],
  },
  { id: 4, name: "font-style", values: ["italic", "non-italic"] },
  {
    id: 5,
    name: "font-weigth",
    values: [
      "font-thin",
      "font-extralight",
      "font-light",
      "font-normal",
      "font-medium",
      "font-semibold",
      "font-bold",
      "font-extrabold",
      "font-black",
    ],
  },
  {
    id: 6,
    name: "font-variant-numeric",
    values: [
      "normal-nums",
      "ordinal",
      "slashed-zero",
      "lining-nums",
      "oldstyle-nums",
      "proportional-nums",
      "tabular-nums",
      "diagonal-fractions",
      "stacked-fractions",
    ],
  },

  {
    id: 7,
    name: "tracking",
    values: [
      "tracking-tighter",
      "tracking-tight",
      "tracking-normal",
      "tracking-wide",
      "tracking-wider",
      "tracking-widest",
    ],
  },
  {
    id: 8,
    name: "line-height",
    values: [
      "leading-3",
      "leading-4",
      "leading-5",
      "leading-6",
      "leading-7",
      "leading-8",
      "leading-9",
      "leading-10",
      "leading-none",
      "leading-tight",
      "leading-snug",
      "leading-normal",
      "leading-relaxed",
      "leading-loose",
    ],
  },
  {
    id: 9,
    name: "list-style-type",
    values: ["list-none", "list-disc", "list-decimal"],
  },
  {
    id: 10,
    name: "list-style-position",
    values: ["list-inside", "list-outside"],
  },

  {
    id: 11,
    name: "text-alignment",
    values: ["text-left", "text-center", "text-right", "text-justify"],
  },
  {
    id: 12,
    name: "text-color",
    values: [
      "text-inherit",
      "text-current",
      "text-transparent",
      "text-black",
      "text-white",
      "text-slate-50",
      "text-slate-100",
      "text-slate-200",
      "text-slate-300",
      "text-slate-400",
      "text-slate-500",
      "text-slate-600",
      "text-slate-700",
      "text-slate-800",
      "text-slate-900",
      "text-gray-50",
      "text-gray-100",
      "text-gray-200",
      "text-gray-300",
      "text-gray-400",
      "text-gray-500",
      "text-gray-600",
      "text-gray-700",
      "text-gray-800",
      "text-gray-900",
      "text-zinc-50",
      "text-zinc-100",
      "text-zinc-200",
      "text-zinc-300",
      "text-zinc-400",
      "text-zinc-500",
      "text-zinc-600",
      "text-zinc-700",
      "text-zinc-800",
      "text-zinc-900",
      "text-neutral-50",
      "text-neutral-100",
      "text-neutral-200",
      "text-neutral-300",
      "text-neutral-400",
      "text-neutral-500",
      "text-neutral-600",
      "text-neutral-700",
      "text-neutral-800",
      "text-neutral-900",
      "text-stone-50",
      "text-stone-100",
      "text-stone-200",
      "text-stone-300",
      "text-stone-400",
      "text-stone-500",
      "text-stone-600",
      "text-stone-700",
      "text-stone-800",
      "text-stone-900",
      "text-red-50",
      "text-red-100",
      "text-red-200",
      "text-red-300",
      "text-red-400",
      "text-red-500",
      "text-red-600",
      "text-red-700",
      "text-red-800",
      "text-red-900",
      "text-orange-50",
      "text-orange-100",
      "text-orange-200",
      "text-orange-300",
      "text-orange-400",
      "text-orange-500",
      "text-orange-600",
      "text-orange-700",
      "text-orange-800",
      "text-orange-900",
      "text-amber-50",
      "text-amber-100",
      "text-amber-200",
      "text-amber-300",
      "text-amber-400",
      "text-amber-500",
      "text-amber-600",
      "text-amber-700",
      "text-amber-800",
      "text-amber-900",
      "text-yellow-50",
      "text-yellow-100",
      "text-yellow-200",
      "text-yellow-300",
      "text-yellow-400",
      "text-yellow-500",
      "text-yellow-600",
      "text-yellow-700",
      "text-yellow-800",
      "text-yellow-900",
      "text-lime-50",
      "text-lime-100",
      "text-lime-200",
      "text-lime-300",
      "text-lime-400",
      "text-lime-500",
      "text-lime-600",
      "text-lime-700",
      "text-lime-800",
      "text-lime-900",
      "text-green-50",
      "text-green-100",
      "text-green-200",
      "text-green-300",
      "text-green-400",
      "text-green-500",
      "text-green-600",
      "text-green-700",
      "text-green-800",
      "text-green-900",
      "text-emerald-50",
      "text-emerald-100",
      "text-emerald-200",
      "text-emerald-300",
      "text-emerald-400",
      "text-emerald-500",
      "text-emerald-600",
      "text-emerald-700",
      "text-emerald-800",
      "text-emerald-900",
      "text-teal-50",
      "text-teal-100",
      "text-teal-200",
      "text-teal-300",
      "text-teal-400",
      "text-teal-500",
      "text-teal-600",
      "text-teal-700",
      "text-teal-800",
      "text-teal-900",
      "text-cyan-50",
      "text-cyan-100",
      "text-cyan-200",
      "text-cyan-300",
      "text-cyan-400",
      "text-cyan-500",
      "text-cyan-600",
      "text-cyan-700",
      "text-cyan-800",
      "text-cyan-900",
      "text-sky-50",
      "text-sky-100",
      "text-sky-200",
      "text-sky-300",
      "text-sky-400",
      "text-sky-500",
      "text-sky-600",
      "text-sky-700",
      "text-sky-800",
      "text-sky-900",
      "text-blue-50",
      "text-blue-100",
      "text-blue-200",
      "text-blue-300",
      "text-blue-400",
      "text-blue-500",
      "text-blue-600",
      "text-blue-700",
      "text-blue-800",
      "text-blue-900",
      "text-indigo-50",
      "text-indigo-100",
      "text-indigo-200",
      "text-indigo-300",
      "text-indigo-400",
      "text-indigo-500",
      "text-indigo-600",
      "text-indigo-700",
      "text-indigo-800",
      "text-indigo-900",
      "text-violet-50",
      "text-violet-100",
      "text-violet-200",
      "text-violet-300",
      "text-violet-400",
      "text-violet-500",
      "text-violet-600",
      "text-violet-700",
      "text-violet-800",
      "text-violet-900",
      "text-purple-50",
      "text-purple-100",
      "text-purple-200",
      "text-purple-300",
      "text-purple-400",
      "text-purple-500",
      "text-purple-600",
      "text-purple-700",
      "text-purple-800",
      "text-purple-900",
      "text-fuchsia-50",
      "text-fuchsia-100",
      "text-fuchsia-200",
      "text-fuchsia-300",
      "text-fuchsia-400",
      "text-fuchsia-500",
      "text-fuchsia-600",
      "text-fuchsia-700",
      "text-fuchsia-800",
      "text-fuchsia-900",
      "text-pink-50",
      "text-pink-100",
      "text-pink-200",
      "text-pink-300",
      "text-pink-400",
      "text-pink-500",
      "text-pink-600",
      "text-pink-700",
      "text-pink-800",
      "text-pink-900",
      "text-rose-50",
      "text-rose-100",
      "text-rose-200",
      "text-rose-300",
      "text-rose-400",
      "text-rose-500",
      "text-rose-600",
      "text-rose-700",
      "text-rose-800",
      "text-rose-900",
    ],
  } /* (text color) già messi tutti i colori disponibili */,

  {
    id: 13,
    name: "text-decoration",
    values: ["underline", "overline", "line-through", "no-underline"],
  },
  {
    id: 14,
    name: "text-decoration-color",
    values: [
      "decoration-inherit",
      "decoration-current",
      "decoration-transparent",
      "decoration-black",
      "decoration-white",
      "decoration-slate-50",
      "decoration-slate-100",
      "decoration-slate-200",
      "decoration-slate-300",
      "decoration-slate-400",
      "decoration-slate-500",
      "decoration-slate-600",
      "decoration-slate-700",
      "decoration-slate-800",
      "decoration-slate-900",
      "decoration-gray-50",
      "decoration-gray-100",
      "decoration-gray-200",
      "decoration-gray-300",
      "decoration-gray-400",
      "decoration-gray-500",
      "decoration-gray-600",
      "decoration-gray-700",
      "decoration-gray-800",
      "decoration-gray-900",
      "decoration-zinc-50",
      "decoration-zinc-100",
      "decoration-zinc-200",
      "decoration-zinc-300",
      "decoration-zinc-400",
      "decoration-zinc-500",
      "decoration-zinc-600",
      "decoration-zinc-700",
      "decoration-zinc-800",
      "decoration-zinc-900",
      "decoration-neutral-50",
      "decoration-neutral-100",
      "decoration-neutral-200",
      "decoration-neutral-300",
      "decoration-neutral-400",
      "decoration-neutral-500",
      "decoration-neutral-600",
      "decoration-neutral-700",
      "decoration-neutral-800",
      "decoration-neutral-900",
      "decoration-stone-50",
      "decoration-stone-100",
      "decoration-stone-200",
      "decoration-stone-300",
      "decoration-stone-400",
      "decoration-stone-500",
      "decoration-stone-600",
      "decoration-stone-700",
      "decoration-stone-800",
      "decoration-stone-900",
      "decoration-red-50",
      "decoration-red-100",
      "decoration-red-200",
      "decoration-red-300",
      "decoration-red-400",
      "decoration-red-500",
      "decoration-red-600",
      "decoration-red-700",
      "decoration-red-800",
      "decoration-red-900",
      "decoration-orange-50",
      "decoration-orange-100",
      "decoration-orange-200",
      "decoration-orange-300",
      "decoration-orange-400",
      "decoration-orange-500",
      "decoration-orange-600",
      "decoration-orange-700",
      "decoration-orange-800",
      "decoration-orange-900",
      "decoration-amber-50",
      "decoration-amber-100",
      "decoration-amber-200",
      "decoration-amber-300",
      "decoration-amber-400",
      "decoration-amber-500",
      "decoration-amber-600",
      "decoration-amber-700",
      "decoration-amber-800",
      "decoration-amber-900",
      "decoration-yellow-50",
      "decoration-yellow-100",
      "decoration-yellow-200",
      "decoration-yellow-300",
      "decoration-yellow-400",
      "decoration-yellow-500",
      "decoration-yellow-600",
      "decoration-yellow-700",
      "decoration-yellow-800",
      "decoration-yellow-900",
      "decoration-lime-50",
      "decoration-lime-100",
      "decoration-lime-200",
      "decoration-lime-300",
      "decoration-lime-400",
      "decoration-lime-500",
      "decoration-lime-600",
      "decoration-lime-700",
      "decoration-lime-800",
      "decoration-lime-900",
      "decoration-green-50",
      "decoration-green-100",
      "decoration-green-200",
      "decoration-green-300",
      "decoration-green-400",
      "decoration-green-500",
      "decoration-green-600",
      "decoration-green-700",
      "decoration-green-800",
      "decoration-green-900",
      "decoration-emerald-50",
      "decoration-emerald-100",
      "decoration-emerald-200",
      "decoration-emerald-300",
      "decoration-emerald-400",
      "decoration-emerald-500",
      "decoration-emerald-600",
      "decoration-emerald-700",
      "decoration-emerald-800",
      "decoration-emerald-900",
      "decoration-teal-50",
      "decoration-teal-100",
      "decoration-teal-200",
      "decoration-teal-300",
      "decoration-teal-400",
      "decoration-teal-500",
      "decoration-teal-600",
      "decoration-teal-700",
      "decoration-teal-800",
      "decoration-teal-900",
      "decoration-cyan-50",
      "decoration-cyan-100",
      "decoration-cyan-200",
      "decoration-cyan-300",
      "decoration-cyan-400",
      "decoration-cyan-500",
      "decoration-cyan-600",
      "decoration-cyan-700",
      "decoration-cyan-800",
      "decoration-cyan-900",
      "decoration-sky-50",
      "decoration-sky-100",
      "decoration-sky-200",
      "decoration-sky-300",
      "decoration-sky-400",
      "decoration-sky-500",
      "decoration-sky-600",
      "decoration-sky-700",
      "decoration-sky-800",
      "decoration-sky-900",
      "decoration-blue-50",
      "decoration-blue-100",
      "decoration-blue-200",
      "decoration-blue-300",
      "decoration-blue-400",
      "decoration-blue-500",
      "decoration-blue-600",
      "decoration-blue-700",
      "decoration-blue-800",
      "decoration-blue-900",
      "decoration-indigo-50",
      "decoration-indigo-100",
      "decoration-indigo-200",
      "decoration-indigo-300",
      "decoration-indigo-400",
      "decoration-indigo-500",
      "decoration-indigo-600",
      "decoration-indigo-700",
      "decoration-indigo-800",
      "decoration-indigo-900",
      "decoration-violet-50",
      "decoration-violet-100",
      "decoration-violet-200",
      "decoration-violet-300",
      "decoration-violet-400",
      "decoration-violet-500",
      "decoration-violet-600",
      "decoration-violet-700",
      "decoration-violet-800",
      "decoration-violet-900",
      "decoration-purple-50",
      "decoration-purple-100",
      "decoration-purple-200",
      "decoration-purple-300",
      "decoration-purple-400",
      "decoration-purple-500",
      "decoration-purple-600",
      "decoration-purple-700",
      "decoration-purple-800",
      "decoration-purple-900",
      "decoration-fuchsia-50",
      "decoration-fuchsia-100",
      "decoration-fuchsia-200",
      "decoration-fuchsia-300",
      "decoration-fuchsia-400",
      "decoration-fuchsia-500",
      "decoration-fuchsia-600",
      "decoration-fuchsia-700",
      "decoration-fuchsia-800",
      "decoration-fuchsia-900",
      "decoration-pink-50",
      "decoration-pink-100",
      "decoration-pink-200",
      "decoration-pink-300",
      "decoration-pink-400",
      "decoration-pink-500",
      "decoration-pink-600",
      "decoration-pink-700",
      "decoration-pink-800",
      "decoration-pink-900",
      "decoration-rose-50",
      "decoration-rose-100",
      "decoration-rose-200",
      "decoration-rose-300",
      "decoration-rose-400",
      "decoration-rose-500",
      "decoration-rose-600",
      "decoration-rose-700",
      "decoration-rose-800",
      "decoration-rose-900",
    ],
  } /* (text decoration color) ho già messo TUTTO i colori disponibili */,
  {
    id: 15,
    name: "text-decoration-style",
    values: [
      "decoration-solid",
      "decoration-double",
      "decoration-dotted",
      "decoration-dashed",
      "decoration-wavy",
    ],
  },
  {
    id: 16,
    name: "text-decoration-thickness",
    values: [
      "decoration-auto",
      "decoration-from-font",
      "decoration-0",
      "decoration-1",
      "decoration-2",
      "decoration-4",
      "decoration-8",
    ],
  },

  {
    id: 17,
    name: "text-underline-offset",
    values: [
      "underline-offset-auto",
      "underline-offset-0",
      "underline-offset-1",
      "underline-offset-2",
      "underline-offset-4",
      "underline-offset-8",
    ],
  },
  {
    id: 18,
    name: "text-transform",
    values: ["uppercase", "lowercase", "capitalize", "normal-case"],
  },
  {
    id: 19,
    name: "text-overflow",
    values: ["truncate", "text-ellipsis", "text-clip"],
  },
  {
    id: 20,
    name: "indent",
    values: [
      "indent-0",
      "index-px",
      "indent-0.5",
      "index-1",
      "index-1.5",
      "index-2",
      "index-2.5",
      "index-3",
      "index-3.5",
      "index-4",
      "index-5",
      "index-6",
      "index-7",
      "index-8",
      "index-9",
      "index-10",
      "index-11",
      "index-12",
      "index-14",
      "index-16",
      "index-20",
      "index-24",
      "index-28",
      "index-32",
      "index-36",
      "index-40",
      "index-44",
      "index-48",
      "index-52",
      "index-56",
      "index-60",
      "index-64",
      "index-72",
      "index-80",
      "index-96",
    ],
  },
  {
    id: 21,
    name: "vertical-alignment",
    values: [
      "align-baseline",
      "align-top",
      "align-middle",
      "align-bottom",
      "align-text-top",
      "align-text-bottom",
      "align-sub",
      "align-super",
    ],
  },
  {
    id: 22,
    name: "whitespace",
    values: [
      "whitespace-normal",
      "whitespace-nowrap",
      "whitespace-pre",
      "whitespace-pre-line",
      "whitespace-pre-wrap",
    ],
  },
  {
    id: 23,
    name: "word-break",
    values: ["break-normal", "break-words", "break-all"],
  },
  { id: 24, name: "content", values: ["content-none "] },
];

/* ok */
export const background = [
  {
    id: 1,
    name: "bg-attachment",
    values: ["bg-fixed", "bg-local", "bg-scroll"],
  },
  {
    id: 2,
    name: "bg-clip",
    values: [
      "bg-clip-border",
      "bg-clip-padding",
      "bg-clip-content",
      "bg-clip-text",
    ],
  },
  {
    id: 3,
    name: "bg-color",
    values: [
      "bg-inherit",
      "bg-current",
      "bg-transparent",
      "bg-black",
      "bg-white",
      "bg-slate-50",
      "bg-slate-100",
      "bg-slate-200",
      "bg-slate-300",
      "bg-slate-400",
      "bg-slate-500",
      "bg-slate-600",
      "bg-slate-700",
      "bg-slate-800",
      "bg-slate-900",
      "bg-slate-50",
      "bg-slate-100",
      "bg-slate-200",
      "bg-slate-300",
      "bg-slate-400",
      "bg-slate-500",
      "bg-slate-600",
      "bg-slate-700",
      "bg-slate-800",
      "bg-slate-900",
      "bg-gray-50",
      "bg-gray-100",
      "bg-gray-200",
      "bg-gray-300",
      "bg-gray-400",
      "bg-gray-500",
      "bg-gray-600",
      "bg-gray-700",
      "bg-gray-800",
      "bg-gray-900",
      "bg-zinc-50",
      "bg-zinc-100",
      "bg-zinc-200",
      "bg-zinc-300",
      "bg-zinc-400",
      "bg-zinc-500",
      "bg-zinc-600",
      "bg-zinc-700",
      "bg-zinc-800",
      "bg-zinc-900",
      "bg-neutral-50",
      "bg-neutral-100",
      "bg-neutral-200",
      "bg-neutral-300",
      "bg-neutral-400",
      "bg-neutral-500",
      "bg-neutral-600",
      "bg-neutral-700",
      "bg-neutral-800",
      "bg-neutral-900",
      "bg-stone-50",
      "bg-stone-100",
      "bg-stone-200",
      "bg-stone-300",
      "bg-stone-400",
      "bg-stone-500",
      "bg-stone-600",
      "bg-stone-700",
      "bg-stone-800",
      "bg-stone-900",
      "bg-red-50",
      "bg-red-100",
      "bg-red-200",
      "bg-red-300",
      "bg-red-400",
      "bg-red-500",
      "bg-red-600",
      "bg-red-700",
      "bg-red-800",
      "bg-red-900",
      "bg-orange-50",
      "bg-orange-100",
      "bg-orange-200",
      "bg-orange-300",
      "bg-orange-400",
      "bg-orange-500",
      "bg-orange-600",
      "bg-orange-700",
      "bg-orange-800",
      "bg-orange-900",
      "bg-amber-50",
      "bg-amber-100",
      "bg-amber-200",
      "bg-amber-300",
      "bg-amber-400",
      "bg-amber-500",
      "bg-amber-600",
      "bg-amber-700",
      "bg-amber-800",
      "bg-amber-900",
      "bg-yellow-50",
      "bg-yellow-100",
      "bg-yellow-200",
      "bg-yellow-300",
      "bg-yellow-400",
      "bg-yellow-500",
      "bg-yellow-600",
      "bg-yellow-700",
      "bg-yellow-800",
      "bg-yellow-900",
      "bg-lime-50",
      "bg-lime-100",
      "bg-lime-200",
      "bg-lime-300",
      "bg-lime-400",
      "bg-lime-500",
      "bg-lime-600",
      "bg-lime-700",
      "bg-lime-800",
      "bg-lime-900",
      "bg-green-50",
      "bg-green-100",
      "bg-green-200",
      "bg-green-300",
      "bg-green-400",
      "bg-green-500",
      "bg-green-600",
      "bg-green-700",
      "bg-green-800",
      "bg-green-900",
      "bg-emerald-50",
      "bg-emerald-100",
      "bg-emerald-200",
      "bg-emerald-300",
      "bg-emerald-400",
      "bg-emerald-500",
      "bg-emerald-600",
      "bg-emerald-700",
      "bg-emerald-800",
      "bg-emerald-900",
      "bg-teal-50",
      "bg-teal-100",
      "bg-teal-200",
      "bg-teal-300",
      "bg-teal-400",
      "bg-teal-500",
      "bg-teal-600",
      "bg-teal-700",
      "bg-teal-800",
      "bg-teal-900",
      "bg-cyan-50",
      "bg-cyan-100",
      "bg-cyan-200",
      "bg-cyan-300",
      "bg-cyan-400",
      "bg-cyan-500",
      "bg-cyan-600",
      "bg-cyan-700",
      "bg-cyan-800",
      "bg-cyan-900",
      "bg-sky-50",
      "bg-sky-100",
      "bg-sky-200",
      "bg-sky-300",
      "bg-sky-400",
      "bg-sky-500",
      "bg-sky-600",
      "bg-sky-700",
      "bg-sky-800",
      "bg-sky-900",
      "bg-blue-50",
      "bg-blue-100",
      "bg-blue-200",
      "bg-blue-300",
      "bg-blue-400",
      "bg-blue-500",
      "bg-blue-600",
      "bg-blue-700",
      "bg-blue-800",
      "bg-blue-900",
      "bg-indigo-50",
      "bg-indigo-100",
      "bg-indigo-200",
      "bg-indigo-300",
      "bg-indigo-400",
      "bg-indigo-500",
      "bg-indigo-600",
      "bg-indigo-700",
      "bg-indigo-800",
      "bg-indigo-900",
      "bg-violet-50",
      "bg-violet-100",
      "bg-violet-200",
      "bg-violet-300",
      "bg-violet-400",
      "bg-violet-500",
      "bg-violet-600",
      "bg-violet-700",
      "bg-violet-800",
      "bg-violet-900",
      "bg-purple-50",
      "bg-purple-100",
      "bg-purple-200",
      "bg-purple-300",
      "bg-purple-400",
      "bg-purple-500",
      "bg-purple-600",
      "bg-purple-700",
      "bg-purple-800",
      "bg-purple-900",
      "bg-fuchsia-50",
      "bg-fuchsia-100",
      "bg-fuchsia-200",
      "bg-fuchsia-300",
      "bg-fuchsia-400",
      "bg-fuchsia-500",
      "bg-fuchsia-600",
      "bg-fuchsia-700",
      "bg-fuchsia-800",
      "bg-fuchsia-900",
      "bg-pink-50",
      "bg-pink-100",
      "bg-pink-200",
      "bg-pink-300",
      "bg-pink-400",
      "bg-pink-500",
      "bg-pink-600",
      "bg-pink-700",
      "bg-pink-800",
      "bg-pink-900",
      "bg-rose-50",
      "bg-rose-100",
      "bg-rose-200",
      "bg-rose-300",
      "bg-rose-400",
      "bg-rose-500",
      "bg-rose-600",
      "bg-rose-700",
      "bg-rose-800",
      "bg-rose-900",
    ],
  },
  {
    id: 4,
    name: "bg-opacity",
    values: ["/50", "/75", "/100"],
  } /* bg-gray-400/50   --->   /100 /75 /50 */,
  {
    id: 5,
    name: "bg-origin",
    values: ["bg-origin-border", "bg-origin-padding", "bg-origin-content"],
  },
  {
    id: 6,
    name: "bg-position",
    values: [
      "bg-bottom",
      "bg-center",
      "bg-left",
      "bg-left-bottom",
      "bg-left-top",
      "bg-right",
      "bg-right-bottom",
      "bg-right-top",
      "bg-top",
    ],
  },
  {
    id: 7,
    name: "bg-repeat",
    values: [
      "bg-repeat",
      "bg-no-repeat",
      "bg-repeat-x",
      "bg-repeat-y",
      "bg-repeat-round",
      "bg-repeat-space",
    ],
  },
  {
    id: 8,
    name: "bg-image",
    values: [
      "bg-none",
      "bg-gradient-to-t",
      "bg-gradient-to-tr",
      "bg-gradient-to-r",
      "bg-gradient-to-br",
      "bg-gradient-to-b",
      "bg-gradient-to-bl",
      "bg-gradient-to-l",
      "bg-gradient-to-tl",
    ],
  } /* Background Image a cui va aggiunto from-purple-500 to-pink-500 */,
  {
    id: 9,
    name: "gradient-color-stops",
    values: [
      "from-inherit",
      "from-current",
      "from-transparent",
      "from-black",
      "from-white",
      "from-slate-50" /* from-[...]-[...] */,
      "via-inherit",
      "via-current",
      "via-transparent",
      "via-black",
      "via-white",
      "via-slate-50" /* via-[...]-[...] */,
      "to-inherit",
      "to-current",
      "to-transparent",
      "to-black",
      "to-white",
      "to-slate-50" /* to-[...]-[...] */,
    ],
  } /* tutti gli altri colori si arrangiano... */,
];

/* ok */
export const border = [
  {
    id: 1,
    name: "border-radius",
    values: [
      "rounded-non",
      "rounded-sm",
      "rounded",
      "rounded-md",
      "rounded-lg",
      "rounded-xl",
      "rounded-2xl",
      "rounded-3xl",
      "rounded-full",
      "rounded-t-none",
      "rounded-t-sm",
      "rounded-t",
      "rounded-t-md",
      "rounded-t-lg",
      "rounded-t-xl",
      "rounded-t-2xl",
      "rounded-t-3xl",
      "rounded-t-full",
      "rounded-r-none",
      "rounded-t-sm",
      "rounded-r",
      "rounded-r-md",
      "rounded-r-lg",
      "rounded-r-xl",
      "rounded-r-2xl",
      "rounded-r-3xl",
      "rounded-r-full",
      "rounded-b-none",
      "rounded-b-sm",
      "rounded-b",
      "rounded-b-md",
      "rounded-b-lg",
      "rounded-b-xl",
      "rounded-b-2xl",
      "rounded-b-3xl",
      "rounded-b-full",
      "rounded-l-none",
      "rounded-l-sm",
      "rounded-l",
      "rounded-l-md",
      "rounded-l-lg",
      "rounded-l-xl",
      "rounded-l-2xl",
      "rounded-l-3xl",
      "rounded-l-full",
      "rounded-tl-none",
      "rounded-tl-sm",
      "rounded-tl",
      "rounded-tl-md",
      "rounded-tl-lg",
      "rounded-tl-xl",
      "rounded-tl-2xl",
      "rounded-tl-3xl",
      "rounded-tl-full",
      "rounded-tr-none",
      "rounded-tr-sm",
      "rounded-tr",
      "rounded-tr-md",
      "rounded-tr-lg",
      "rounded-tr-xl",
      "rounded-tr-2xl",
      "rounded-tr-3xl",
      "rounded-tr-full",
      "rounded-bl-none",
      "rounded-bl-sm",
      "rounded-bl",
      "rounded-bl-md",
      "rounded-bl-lg",
      "rounded-bl-xl",
      "rounded-bl-2xl",
      "rounded-bl-3xl",
      "rounded-bl-full",
      "rounded-br-none",
      "rounded-br-sm",
      "rounded-br",
      "rounded-br-md",
      "rounded-br-lg",
      "rounded-br-xl",
      "rounded-br-2xl",
      "rounded-br-3xl",
      "rounded-br-full",
    ],
  },
  {
    id: 2,
    name: "border-width",
    values: ["border-0", "border-2", "border-4", "border-8", "border"],
  },
  {
    id: 3,
    name: "border-width-x",
    values: [
      "border-x-0",
      "border-x-2",
      "border-x-4",
      "border-x-8",
      "border-x",
    ],
  },
  {
    id: 4,
    name: "border-width-y",
    values: [
      "border-y-0",
      "border-y-2",
      "border-y-4",
      "border-y-8",
      "border-y",
    ],
  },
  {
    id: 5,
    name: "border-width-t",
    values: [
      "border-t-0",
      "border-t-2",
      "border-t-4",
      "border-t-8",
      "border-t",
    ],
  },
  {
    id: 6,
    name: "border-width-r",
    values: [
      "border-r-0",
      "border-r-2",
      "border-r-4",
      "border-r-8",
      "border-r",
    ],
  },
  {
    id: 7,
    name: "border-width-b",
    values: [
      "border-b-0",
      "border-b-2",
      "border-b-4",
      "border-b-8",
      "border-b",
    ],
  },
  {
    id: 8,
    name: "border-width-l",
    values: [
      "border-l-0",
      "border-l-2",
      "border-l-4",
      "border-l-8",
      "border-l",
    ],
  },
  {
    id: 9,
    name: "border-color",
    values: [
      "border-inherit",
      "border-current",
      "border-transparent",
      "border-black",
      "border-white",
      "border-slate-50" /* border-[...]-[...] */,
      "border-t-slate-50" /* border-t-[...]-[...] */,
      "border-b-slate-50" /* border-b-[...]-[...] */,
      "border-x-slate-50" /* border-x-[...]-[...] */,
      "border-y-slate-50" /* border-y-[...]-[...] */,
      "border-r-slate-50" /* border-r-[...]-[...] */,
      "border-l-slate-50" /* border-l-[...]-[...] */,
    ],
  } /* x,y,t,b,r,l per tutti i colori */,
  {
    id: 10,
    name: "border-style",
    values: [
      "border-solid",
      "border-dashed",
      "border-dotted",
      "border-double",
      "border-hidden",
      "border-none",
    ],
  },

  {
    id: 11,
    name: "divide-width",
    values: [
      "divide-x-0",
      "divide-x-2",
      "divide-x-4",
      "divide-x-8",
      "divide-x",
      "divide-y-0",
      "divide-y-2",
      "divide-y-4",
      "divide-y-8",
      "divide-y-reverse",
      "divide-x-reverse",
    ],
  },
  {
    id: 12,
    name: "divide-color",
    values: [
      "divide-inherit",
      "divide-current",
      "divide-transparent",
      "divide-black",
      "divide-white",
      "divide-slate-50",
      "divide-slate-100",
      "divide-slate-200",
      "divide-slate-300",
      "divide-slate-400",
      "divide-slate-500",
      "divide-slate-600",
      "divide-slate-700",
      "divide-slate-800",
      "divide-slate-900",
      "divide-gray-50",
      "divide-gray-100",
      "divide-gray-200",
      "divide-gray-300",
      "divide-gray-400",
      "divide-gray-500",
      "divide-gray-600",
      "divide-gray-700",
      "divide-gray-800",
      "divide-gray-900",
      "divide-zinc-50",
      "divide-zinc-100",
      "divide-zinc-200",
      "divide-zinc-300",
      "divide-zinc-400",
      "divide-zinc-500",
      "divide-zinc-600",
      "divide-zinc-700",
      "divide-zinc-800",
      "divide-zinc-900",
      "divide-neutral-50",
      "divide-neutral-100",
      "divide-neutral-200",
      "divide-neutral-300",
      "divide-neutral-400",
      "divide-neutral-500",
      "divide-neutral-600",
      "divide-neutral-700",
      "divide-neutral-800",
      "divide-neutral-900",
      "divide-stone-50",
      "divide-stone-100",
      "divide-stone-200",
      "divide-stone-300",
      "divide-stone-400",
      "divide-stone-500",
      "divide-stone-600",
      "divide-stone-700",
      "divide-stone-800",
      "divide-stone-900",
      "divide-red-50",
      "divide-red-100",
      "divide-red-200",
      "divide-red-300",
      "divide-red-400",
      "divide-red-500",
      "divide-red-600",
      "divide-red-700",
      "divide-red-800",
      "divide-red-900",
      "divide-orange-50",
      "divide-orange-100",
      "divide-orange-200",
      "divide-orange-300",
      "divide-orange-400",
      "divide-orange-500",
      "divide-orange-600",
      "divide-orange-700",
      "divide-orange-800",
      "divide-orange-900",
      "divide-amber-50",
      "divide-amber-100",
      "divide-amber-200",
      "divide-amber-300",
      "divide-amber-400",
      "divide-amber-500",
      "divide-amber-600",
      "divide-amber-700",
      "divide-amber-800",
      "divide-amber-900",
      "divide-yellow-50",
      "divide-yellow-100",
      "divide-yellow-200",
      "divide-yellow-300",
      "divide-yellow-400",
      "divide-yellow-500",
      "divide-yellow-600",
      "divide-yellow-700",
      "divide-yellow-800",
      "divide-yellow-900",
      "divide-lime-50",
      "divide-lime-100",
      "divide-lime-200",
      "divide-lime-300",
      "divide-lime-400",
      "divide-lime-500",
      "divide-lime-600",
      "divide-lime-700",
      "divide-lime-800",
      "divide-lime-900",
      "divide-green-50",
      "divide-green-100",
      "divide-green-200",
      "divide-green-300",
      "divide-green-400",
      "divide-green-500",
      "divide-green-600",
      "divide-green-700",
      "divide-green-800",
      "divide-green-900",
      "divide-emerald-50",
      "divide-emerald-100",
      "divide-emerald-200",
      "divide-emerald-300",
      "divide-emerald-400",
      "divide-emerald-500",
      "divide-emerald-600",
      "divide-emerald-700",
      "divide-emerald-800",
      "divide-emerald-900",
      "divide-teal-50",
      "divide-teal-100",
      "divide-teal-200",
      "divide-teal-300",
      "divide-teal-400",
      "divide-teal-500",
      "divide-teal-600",
      "divide-teal-700",
      "divide-teal-800",
      "divide-teal-900",
      "divide-cyan-50",
      "divide-cyan-100",
      "divide-cyan-200",
      "divide-cyan-300",
      "divide-cyan-400",
      "divide-cyan-500",
      "divide-cyan-600",
      "divide-cyan-700",
      "divide-cyan-800",
      "divide-cyan-900",
      "divide-sky-50",
      "divide-sky-100",
      "divide-sky-200",
      "divide-sky-300",
      "divide-sky-400",
      "divide-sky-500",
      "divide-sky-600",
      "divide-sky-700",
      "divide-sky-800",
      "divide-sky-900",
      "divide-blue-50",
      "divide-blue-100",
      "divide-blue-200",
      "divide-blue-300",
      "divide-blue-400",
      "divide-blue-500",
      "divide-blue-600",
      "divide-blue-700",
      "divide-blue-800",
      "divide-blue-900",
      "divide-indigo-50",
      "divide-indigo-100",
      "divide-indigo-200",
      "divide-indigo-300",
      "divide-indigo-400",
      "divide-indigo-500",
      "divide-indigo-600",
      "divide-indigo-700",
      "divide-indigo-800",
      "divide-indigo-900",
      "divide-violet-50",
      "divide-violet-100",
      "divide-violet-200",
      "divide-violet-300",
      "divide-violet-400",
      "divide-violet-500",
      "divide-violet-600",
      "divide-violet-700",
      "divide-violet-800",
      "divide-violet-900",
      "divide-purple-50",
      "divide-purple-100",
      "divide-purple-200",
      "divide-purple-300",
      "divide-purple-400",
      "divide-purple-500",
      "divide-purple-600",
      "divide-purple-700",
      "divide-purple-800",
      "divide-purple-900",
      "divide-fuchsia-50",
      "divide-fuchsia-100",
      "divide-fuchsia-200",
      "divide-fuchsia-300",
      "divide-fuchsia-400",
      "divide-fuchsia-500",
      "divide-fuchsia-600",
      "divide-fuchsia-700",
      "divide-fuchsia-800",
      "divide-fuchsia-900",
      "divide-pink-50",
      "divide-pink-100",
      "divide-pink-200",
      "divide-pink-300",
      "divide-pink-400",
      "divide-pink-500",
      "divide-pink-600",
      "divide-pink-700",
      "divide-pink-800",
      "divide-pink-900",
      "divide-rose-50",
      "divide-rose-100",
      "divide-rose-200",
      "divide-rose-300",
      "divide-rose-400",
      "divide-rose-500",
      "divide-rose-600",
      "divide-rose-700",
      "divide-rose-800",
      "divide-rose-900",
    ],
  },
  {
    id: 13,
    name: "divide-style",
    values: [
      "divide-solid",
      "divide-dashed ",
      "divide-dotted ",
      "divide-double ",
      "divide-none",
    ],
  },

  {
    id: 14,
    name: "outline-width",
    values: ["outline-0", "outline-2", "outline-4", "outline-8"],
  },
  {
    id: 15,
    name: "outline-color",
    values: [
      "outline-inherit",
      "outline-current",
      "outline-transparent",
      "outline-black",
      "outline-white",
      "outline-inherit",
      "outline-current",
      "outline-transparent",
      "outline-black",
      "outline-white",
      "outline-slate-50",
      "outline-slate-100",
      "outline-slate-200",
      "outline-slate-300",
      "outline-slate-400",
      "outline-slate-500",
      "outline-slate-600",
      "outline-slate-700",
      "outline-slate-800",
      "outline-slate-900",
      "outline-gray-50",
      "outline-gray-100",
      "outline-gray-200",
      "outline-gray-300",
      "outline-gray-400",
      "outline-gray-500",
      "outline-gray-600",
      "outline-gray-700",
      "outline-gray-800",
      "outline-gray-900",
      "outline-zinc-50",
      "outline-zinc-100",
      "outline-zinc-200",
      "outline-zinc-300",
      "outline-zinc-400",
      "outline-zinc-500",
      "outline-zinc-600",
      "outline-zinc-700",
      "outline-zinc-800",
      "outline-zinc-900",
      "outline-neutral-50",
      "outline-neutral-100",
      "outline-neutral-200",
      "outline-neutral-300",
      "outline-neutral-400",
      "outline-neutral-500",
      "outline-neutral-600",
      "outline-neutral-700",
      "outline-neutral-800",
      "outline-neutral-900",
      "outline-stone-50",
      "outline-stone-100",
      "outline-stone-200",
      "outline-stone-300",
      "outline-stone-400",
      "outline-stone-500",
      "outline-stone-600",
      "outline-stone-700",
      "outline-stone-800",
      "outline-stone-900",
      "outline-red-50",
      "outline-red-100",
      "outline-red-200",
      "outline-red-300",
      "outline-red-400",
      "outline-red-500",
      "outline-red-600",
      "outline-red-700",
      "outline-red-800",
      "outline-red-900",
      "outline-orange-50",
      "outline-orange-100",
      "outline-orange-200",
      "outline-orange-300",
      "outline-orange-400",
      "outline-orange-500",
      "outline-orange-600",
      "outline-orange-700",
      "outline-orange-800",
      "outline-orange-900",
      "outline-amber-50",
      "outline-amber-100",
      "outline-amber-200",
      "outline-amber-300",
      "outline-amber-400",
      "outline-amber-500",
      "outline-amber-600",
      "outline-amber-700",
      "outline-amber-800",
      "outline-amber-900",
      "outline-yellow-50",
      "outline-yellow-100",
      "outline-yellow-200",
      "outline-yellow-300",
      "outline-yellow-400",
      "outline-yellow-500",
      "outline-yellow-600",
      "outline-yellow-700",
      "outline-yellow-800",
      "outline-yellow-900",
      "outline-lime-50",
      "outline-lime-100",
      "outline-lime-200",
      "outline-lime-300",
      "outline-lime-400",
      "outline-lime-500",
      "outline-lime-600",
      "outline-lime-700",
      "outline-lime-800",
      "outline-lime-900",
      "outline-green-50",
      "outline-green-100",
      "outline-green-200",
      "outline-green-300",
      "outline-green-400",
      "outline-green-500",
      "outline-green-600",
      "outline-green-700",
      "outline-green-800",
      "outline-green-900",
      "outline-emerald-50",
      "outline-emerald-100",
      "outline-emerald-200",
      "outline-emerald-300",
      "outline-emerald-400",
      "outline-emerald-500",
      "outline-emerald-600",
      "outline-emerald-700",
      "outline-emerald-800",
      "outline-emerald-900",
      "outline-teal-50",
      "outline-teal-100",
      "outline-teal-200",
      "outline-teal-300",
      "outline-teal-400",
      "outline-teal-500",
      "outline-teal-600",
      "outline-teal-700",
      "outline-teal-800",
      "outline-teal-900",
      "outline-cyan-50",
      "outline-cyan-100",
      "outline-cyan-200",
      "outline-cyan-300",
      "outline-cyan-400",
      "outline-cyan-500",
      "outline-cyan-600",
      "outline-cyan-700",
      "outline-cyan-800",
      "outline-cyan-900",
      "outline-sky-50",
      "outline-sky-100",
      "outline-sky-200",
      "outline-sky-300",
      "outline-sky-400",
      "outline-sky-500",
      "outline-sky-600",
      "outline-sky-700",
      "outline-sky-800",
      "outline-sky-900",
      "outline-blue-50",
      "outline-blue-100",
      "outline-blue-200",
      "outline-blue-300",
      "outline-blue-400",
      "outline-blue-500",
      "outline-blue-600",
      "outline-blue-700",
      "outline-blue-800",
      "outline-blue-900",
      "outline-indigo-50",
      "outline-indigo-100",
      "outline-indigo-200",
      "outline-indigo-300",
      "outline-indigo-400",
      "outline-indigo-500",
      "outline-indigo-600",
      "outline-indigo-700",
      "outline-indigo-800",
      "outline-indigo-900",
      "outline-violet-50",
      "outline-violet-100",
      "outline-violet-200",
      "outline-violet-300",
      "outline-violet-400",
      "outline-violet-500",
      "outline-violet-600",
      "outline-violet-700",
      "outline-violet-800",
      "outline-violet-900",
      "outline-purple-50",
      "outline-purple-100",
      "outline-purple-200",
      "outline-purple-300",
      "outline-purple-400",
      "outline-purple-500",
      "outline-purple-600",
      "outline-purple-700",
      "outline-purple-800",
      "outline-purple-900",
      "outline-fuchsia-50",
      "outline-fuchsia-100",
      "outline-fuchsia-200",
      "outline-fuchsia-300",
      "outline-fuchsia-400",
      "outline-fuchsia-500",
      "outline-fuchsia-600",
      "outline-fuchsia-700",
      "outline-fuchsia-800",
      "outline-fuchsia-900",
      "outline-pink-50",
      "outline-pink-100",
      "outline-pink-200",
      "outline-pink-300",
      "outline-pink-400",
      "outline-pink-500",
      "outline-pink-600",
      "outline-pink-700",
      "outline-pink-800",
      "outline-pink-900",
      "outline-rose-50",
      "outline-rose-100",
      "outline-rose-200",
      "outline-rose-300",
      "outline-rose-400",
      "outline-rose-500",
      "outline-rose-600",
      "outline-rose-700",
      "outline-rose-800",
      "outline-rose-900",
    ],
  },
  {
    id: 16,
    name: "outline-style",
    values: [
      "outline-none",
      "outline",
      "outline-dashed ",
      "outline-dotted ",
      "outline-double ",
      "outline-hidden",
    ],
  },
  {
    id: 17,
    name: "outline-offset",
    values: [
      "outline-offset-0",
      "outline-offset-2",
      "outline-offset-4",
      "outline-offset-8",
    ],
  },

  {
    id: 18,
    name: "ring-width",
    values: [
      "ring",
      "ring-0",
      "ring-1",
      "ring-2",
      "ring-4",
      "ring-8",
      "ring-inset",
    ],
  },
  {
    id: 19,
    name: "ring-color",
    values: [
      "ring-inherit",
      "ring-current",
      "ring-transparent",
      "ring-black",
      "ring-white",
      "ring-slate-50",
      "ring-slate-100",
      "ring-slate-200",
      "ring-slate-300",
      "ring-slate-400",
      "ring-slate-500",
      "ring-slate-600",
      "ring-slate-700",
      "ring-slate-800",
      "ring-slate-900",
      "ring-gray-50",
      "ring-gray-100",
      "ring-gray-200",
      "ring-gray-300",
      "ring-gray-400",
      "ring-gray-500",
      "ring-gray-600",
      "ring-gray-700",
      "ring-gray-800",
      "ring-gray-900",
      "ring-zinc-50",
      "ring-zinc-100",
      "ring-zinc-200",
      "ring-zinc-300",
      "ring-zinc-400",
      "ring-zinc-500",
      "ring-zinc-600",
      "ring-zinc-700",
      "ring-zinc-800",
      "ring-zinc-900",
      "ring-neutral-50",
      "ring-neutral-100",
      "ring-neutral-200",
      "ring-neutral-300",
      "ring-neutral-400",
      "ring-neutral-500",
      "ring-neutral-600",
      "ring-neutral-700",
      "ring-neutral-800",
      "ring-neutral-900",
      "ring-stone-50",
      "ring-stone-100",
      "ring-stone-200",
      "ring-stone-300",
      "ring-stone-400",
      "ring-stone-500",
      "ring-stone-600",
      "ring-stone-700",
      "ring-stone-800",
      "ring-stone-900",
      "ring-red-50",
      "ring-red-100",
      "ring-red-200",
      "ring-red-300",
      "ring-red-400",
      "ring-red-500",
      "ring-red-600",
      "ring-red-700",
      "ring-red-800",
      "ring-red-900",
      "ring-orange-50",
      "ring-orange-100",
      "ring-orange-200",
      "ring-orange-300",
      "ring-orange-400",
      "ring-orange-500",
      "ring-orange-600",
      "ring-orange-700",
      "ring-orange-800",
      "ring-orange-900",
      "ring-amber-50",
      "ring-amber-100",
      "ring-amber-200",
      "ring-amber-300",
      "ring-amber-400",
      "ring-amber-500",
      "ring-amber-600",
      "ring-amber-700",
      "ring-amber-800",
      "ring-amber-900",
      "ring-yellow-50",
      "ring-yellow-100",
      "ring-yellow-200",
      "ring-yellow-300",
      "ring-yellow-400",
      "ring-yellow-500",
      "ring-yellow-600",
      "ring-yellow-700",
      "ring-yellow-800",
      "ring-yellow-900",
      "ring-lime-50",
      "ring-lime-100",
      "ring-lime-200",
      "ring-lime-300",
      "ring-lime-400",
      "ring-lime-500",
      "ring-lime-600",
      "ring-lime-700",
      "ring-lime-800",
      "ring-lime-900",
      "ring-green-50",
      "ring-green-100",
      "ring-green-200",
      "ring-green-300",
      "ring-green-400",
      "ring-green-500",
      "ring-green-600",
      "ring-green-700",
      "ring-green-800",
      "ring-green-900",
      "ring-emerald-50",
      "ring-emerald-100",
      "ring-emerald-200",
      "ring-emerald-300",
      "ring-emerald-400",
      "ring-emerald-500",
      "ring-emerald-600",
      "ring-emerald-700",
      "ring-emerald-800",
      "ring-emerald-900",
      "ring-teal-50",
      "ring-teal-100",
      "ring-teal-200",
      "ring-teal-300",
      "ring-teal-400",
      "ring-teal-500",
      "ring-teal-600",
      "ring-teal-700",
      "ring-teal-800",
      "ring-teal-900",
      "ring-cyan-50",
      "ring-cyan-100",
      "ring-cyan-200",
      "ring-cyan-300",
      "ring-cyan-400",
      "ring-cyan-500",
      "ring-cyan-600",
      "ring-cyan-700",
      "ring-cyan-800",
      "ring-cyan-900",
      "ring-sky-50",
      "ring-sky-100",
      "ring-sky-200",
      "ring-sky-300",
      "ring-sky-400",
      "ring-sky-500",
      "ring-sky-600",
      "ring-sky-700",
      "ring-sky-800",
      "ring-sky-900",
      "ring-blue-50",
      "ring-blue-100",
      "ring-blue-200",
      "ring-blue-300",
      "ring-blue-400",
      "ring-blue-500",
      "ring-blue-600",
      "ring-blue-700",
      "ring-blue-800",
      "ring-blue-900",
      "ring-indigo-50",
      "ring-indigo-100",
      "ring-indigo-200",
      "ring-indigo-300",
      "ring-indigo-400",
      "ring-indigo-500",
      "ring-indigo-600",
      "ring-indigo-700",
      "ring-indigo-800",
      "ring-indigo-900",
      "ring-violet-50",
      "ring-violet-100",
      "ring-violet-200",
      "ring-violet-300",
      "ring-violet-400",
      "ring-violet-500",
      "ring-violet-600",
      "ring-violet-700",
      "ring-violet-800",
      "ring-violet-900",
      "ring-purple-50",
      "ring-purple-100",
      "ring-purple-200",
      "ring-purple-300",
      "ring-purple-400",
      "ring-purple-500",
      "ring-purple-600",
      "ring-purple-700",
      "ring-purple-800",
      "ring-purple-900",
      "ring-fuchsia-50",
      "ring-fuchsia-100",
      "ring-fuchsia-200",
      "ring-fuchsia-300",
      "ring-fuchsia-400",
      "ring-fuchsia-500",
      "ring-fuchsia-600",
      "ring-fuchsia-700",
      "ring-fuchsia-800",
      "ring-fuchsia-900",
      "ring-pink-50",
      "ring-pink-100",
      "ring-pink-200",
      "ring-pink-300",
      "ring-pink-400",
      "ring-pink-500",
      "ring-pink-600",
      "ring-pink-700",
      "ring-pink-800",
      "ring-pink-900",
      "ring-rose-50",
      "ring-rose-100",
      "ring-rose-200",
      "ring-rose-300",
      "ring-rose-400",
      "ring-rose-500",
      "ring-rose-600",
      "ring-rose-700",
      "ring-rose-800",
      "ring-rose-900",
    ],
  } /* tutti fli altri colori divide-colore-gradazione ? */,
  {
    id: 20,
    name: "ring-offset",
    values: [
      "ring-offset-0",
      "ring-offset-1",
      "ring-offset-2",
      "ring-offset-4",
      "ring-offset-8",
    ],
  },
  {
    id: 21,
    name: "ring-offset-color",
    values: [
      "ring-offset-inherit",
      "ring-offset-current",
      "ring-offset-transparent",
      "ring-offset-black",
      "ring-offset-white",
      "ring-offset-slate-50",
      "ring-offset-slate-100",
      "ring-offset-slate-200",
      "ring-offset-slate-300",
      "ring-offset-slate-400",
      "ring-offset-slate-500",
      "ring-offset-slate-600",
      "ring-offset-slate-700",
      "ring-offset-slate-800",
      "ring-offset-slate-900",
      "ring-offset-gray-50",
      "ring-offset-gray-100",
      "ring-offset-gray-200",
      "ring-offset-gray-300",
      "ring-offset-gray-400",
      "ring-offset-gray-500",
      "ring-offset-gray-600",
      "ring-offset-gray-700",
      "ring-offset-gray-800",
      "ring-offset-gray-900",
      "ring-offset-zinc-50",
      "ring-offset-zinc-100",
      "ring-offset-zinc-200",
      "ring-offset-zinc-300",
      "ring-offset-zinc-400",
      "ring-offset-zinc-500",
      "ring-offset-zinc-600",
      "ring-offset-zinc-700",
      "ring-offset-zinc-800",
      "ring-offset-zinc-900",
      "ring-offset-neutral-50",
      "ring-offset-neutral-100",
      "ring-offset-neutral-200",
      "ring-offset-neutral-300",
      "ring-offset-neutral-400",
      "ring-offset-neutral-500",
      "ring-offset-neutral-600",
      "ring-offset-neutral-700",
      "ring-offset-neutral-800",
      "ring-offset-neutral-900",
      "ring-offset-stone-50",
      "ring-offset-stone-100",
      "ring-offset-stone-200",
      "ring-offset-stone-300",
      "ring-offset-stone-400",
      "ring-offset-stone-500",
      "ring-offset-stone-600",
      "ring-offset-stone-700",
      "ring-offset-stone-800",
      "ring-offset-stone-900",
      "ring-offset-red-50",
      "ring-offset-red-100",
      "ring-offset-red-200",
      "ring-offset-red-300",
      "ring-offset-red-400",
      "ring-offset-red-500",
      "ring-offset-red-600",
      "ring-offset-red-700",
      "ring-offset-red-800",
      "ring-offset-red-900",
      "ring-offset-orange-50",
      "ring-offset-orange-100",
      "ring-offset-orange-200",
      "ring-offset-orange-300",
      "ring-offset-orange-400",
      "ring-offset-orange-500",
      "ring-offset-orange-600",
      "ring-offset-orange-700",
      "ring-offset-orange-800",
      "ring-offset-orange-900",
      "ring-offset-amber-50",
      "ring-offset-amber-100",
      "ring-offset-amber-200",
      "ring-offset-amber-300",
      "ring-offset-amber-400",
      "ring-offset-amber-500",
      "ring-offset-amber-600",
      "ring-offset-amber-700",
      "ring-offset-amber-800",
      "ring-offset-amber-900",
      "ring-offset-yellow-50",
      "ring-offset-yellow-100",
      "ring-offset-yellow-200",
      "ring-offset-yellow-300",
      "ring-offset-yellow-400",
      "ring-offset-yellow-500",
      "ring-offset-yellow-600",
      "ring-offset-yellow-700",
      "ring-offset-yellow-800",
      "ring-offset-yellow-900",
      "ring-offset-lime-50",
      "ring-offset-lime-100",
      "ring-offset-lime-200",
      "ring-offset-lime-300",
      "ring-offset-lime-400",
      "ring-offset-lime-500",
      "ring-offset-lime-600",
      "ring-offset-lime-700",
      "ring-offset-lime-800",
      "ring-offset-lime-900",
      "ring-offset-green-50",
      "ring-offset-green-100",
      "ring-offset-green-200",
      "ring-offset-green-300",
      "ring-offset-green-400",
      "ring-offset-green-500",
      "ring-offset-green-600",
      "ring-offset-green-700",
      "ring-offset-green-800",
      "ring-offset-green-900",
      "ring-offset-emerald-50",
      "ring-offset-emerald-100",
      "ring-offset-emerald-200",
      "ring-offset-emerald-300",
      "ring-offset-emerald-400",
      "ring-offset-emerald-500",
      "ring-offset-emerald-600",
      "ring-offset-emerald-700",
      "ring-offset-emerald-800",
      "ring-offset-emerald-900",
      "ring-offset-teal-50",
      "ring-offset-teal-100",
      "ring-offset-teal-200",
      "ring-offset-teal-300",
      "ring-offset-teal-400",
      "ring-offset-teal-500",
      "ring-offset-teal-600",
      "ring-offset-teal-700",
      "ring-offset-teal-800",
      "ring-offset-teal-900",
      "ring-offset-cyan-50",
      "ring-offset-cyan-100",
      "ring-offset-cyan-200",
      "ring-offset-cyan-300",
      "ring-offset-cyan-400",
      "ring-offset-cyan-500",
      "ring-offset-cyan-600",
      "ring-offset-cyan-700",
      "ring-offset-cyan-800",
      "ring-offset-cyan-900",
      "ring-offset-sky-50",
      "ring-offset-sky-100",
      "ring-offset-sky-200",
      "ring-offset-sky-300",
      "ring-offset-sky-400",
      "ring-offset-sky-500",
      "ring-offset-sky-600",
      "ring-offset-sky-700",
      "ring-offset-sky-800",
      "ring-offset-sky-900",
      "ring-offset-blue-50",
      "ring-offset-blue-100",
      "ring-offset-blue-200",
      "ring-offset-blue-300",
      "ring-offset-blue-400",
      "ring-offset-blue-500",
      "ring-offset-blue-600",
      "ring-offset-blue-700",
      "ring-offset-blue-800",
      "ring-offset-blue-900",
      "ring-offset-indigo-50",
      "ring-offset-indigo-100",
      "ring-offset-indigo-200",
      "ring-offset-indigo-300",
      "ring-offset-indigo-400",
      "ring-offset-indigo-500",
      "ring-offset-indigo-600",
      "ring-offset-indigo-700",
      "ring-offset-indigo-800",
      "ring-offset-indigo-900",
      "ring-offset-violet-50",
      "ring-offset-violet-100",
      "ring-offset-violet-200",
      "ring-offset-violet-300",
      "ring-offset-violet-400",
      "ring-offset-violet-500",
      "ring-offset-violet-600",
      "ring-offset-violet-700",
      "ring-offset-violet-800",
      "ring-offset-violet-900",
      "ring-offset-purple-50",
      "ring-offset-purple-100",
      "ring-offset-purple-200",
      "ring-offset-purple-300",
      "ring-offset-purple-400",
      "ring-offset-purple-500",
      "ring-offset-purple-600",
      "ring-offset-purple-700",
      "ring-offset-purple-800",
      "ring-offset-purple-900",
      "ring-offset-fuchsia-50",
      "ring-offset-fuchsia-100",
      "ring-offset-fuchsia-200",
      "ring-offset-fuchsia-300",
      "ring-offset-fuchsia-400",
      "ring-offset-fuchsia-500",
      "ring-offset-fuchsia-600",
      "ring-offset-fuchsia-700",
      "ring-offset-fuchsia-800",
      "ring-offset-fuchsia-900",
      "ring-offset-pink-50",
      "ring-offset-pink-100",
      "ring-offset-pink-200",
      "ring-offset-pink-300",
      "ring-offset-pink-400",
      "ring-offset-pink-500",
      "ring-offset-pink-600",
      "ring-offset-pink-700",
      "ring-offset-pink-800",
      "ring-offset-pink-900",
      "ring-offset-rose-50",
      "ring-offset-rose-100",
      "ring-offset-rose-200",
      "ring-offset-rose-300",
      "ring-offset-rose-400",
      "ring-offset-rose-500",
      "ring-offset-rose-600",
      "ring-offset-rose-700",
      "ring-offset-rose-800",
      "ring-offset-rose-900",
    ],
  } /* tutti fli altri colori divide-colore-gradazione ? */,
];

/* ok */ /* Width + Height */
export const sizing = [
  {
    id: 1,
    name: "width",
    values: [
      "w-0",
      "w-px",
      "w-0.5",
      "w-1",
      "w-1.5",
      "w-2",
      "w-2.5",
      "w-3",
      "w-3.5",
      "w-4",
      "w-5",
      "w-6",
      "w-7",
      "w-8",
      "w-9",
      "w-10",
      "w-11",
      "w-12",
      "w-14",
      "w-16",
      "w-20",
      "w-24",
      "w-28",
      "w-32",
      "w-36",
      "w-40",
      "w-44",
      "w-48",
      "w-52",
      "w-56",
      "w-60",
      "w-64",
      "w-72",
      "w-80",
      "w-96",
      "w-auto",
      "w-1/2",
      "w-1/3",
      "w-2/3",
      "w-1/4",
      "w-2/4",
      "w-3/4",
      "w-1/5",
      "w-2/5",
      "w-3/5",
      "w-4/5",
      "w-1/6",
      "w-2/6",
      "w-3/6",
      "w-4/6",
      "w-5/6",
      "w-1/12",
      "w-2/12",
      "w-3/12",
      "w-4/12",
      "w-5/12",
      "w-5/12",
      "w-6/12",
      "w-7/12",
      "w-8/12," + "w-9/12",
      "w-10/12",
      "w-11/12",
      "w-full",
      "w-screen",
      "w-min",
      "w-max",
      "w-fit",
    ],
  },
  {
    id: 2,
    name: "min-width",
    values: ["min-w-0", "min-w-full", "min-w-min", "min-w-max", "min-w-fit"],
  },
  {
    id: 3,
    name: "max-width",
    values: [
      "max-w-0",
      "max-w-none",
      "max-w-xs",
      "max-w-sm",
      "max-w-lg",
      "max-w-xl",
      "max-w-2xl",
      "max-w-3xl",
      "max-w-4xl",
      "max-w-5xl",
      "max-w-6xl",
      "max-w-7xl",
      "max-w-full",
      "max-w-min",
      "max-w-max",
      "max-w-fit",
      "max-w-prose",
      "max-w-screen-sm",
      "max-w-screen-md",
      "max-w-screen-lg",
      "max-w-screen-xl",
      "max-w-screen-2xl",
    ],
  },
  {
    id: 4,
    name: "height",
    values: [
      "h-0",
      "h-px",
      "h-0.5",
      "h-1",
      "h-1.5",
      "h-2",
      "h-2.5",
      "h-3",
      "h-3.5",
      "h-4",
      "h-5",
      "h-6",
      "h-7",
      "h-8",
      "h-9",
      "h-10",
      "h-11",
      "h-12",
      "h-14",
      "h-16",
      "h-20",
      "h-24",
      "h-28",
      "h-32",
      "h-36",
      "h-40",
      "h-44",
      "h-48",
      "h-52",
      "h-56",
      "h-60",
      "h-64",
      "h-72",
      "h-80",
      "h-96",
      "h-auto",
      "h-1/2",
      "h-1/3",
      "h-2/3",
      "h-1/4",
      "h-2/4",
      "h-3/4",
      "h-1/5",
      "h-2/5",
      "h-3/5",
      "h-4/5",
      "h-1/6",
      "h-2/6",
      "h-3/6",
      "h-4/6",
      "h-5/6",
      "h-1/12",
      "h-2/12",
      "h-3/12",
      "h-4/12",
      "h-5/12",
      "h-5/12",
      "h-6/12",
      "h-7/12",
      "h-8/12," + "h-9/12",
      "h-10/12",
      "h-11/12",
      "h-full",
      "h-screen",
      "h-min",
      "h-max",
      "h-fit",
    ],
  },
  {
    id: 5,
    name: "min-height",
    values: [
      "min-h-0",
      "min-h-full",
      "min-h-screen",
      "min-h-min",
      "min-h-max",
      "min-h-fit",
    ],
  },
  {
    id: 6,
    name: "max-height",
    values: [
      "max-h-0",
      "max-h-px",
      "max-h-0.5",
      "max-h-1",
      "max-h-1.5",
      "max-h-2",
      "max-h-2.5",
      "max-h-3",
      "max-h-3.5",
      "max-h-4",
      "max-h-5",
      "max-h-6",
      "max-h-7",
      "max-h-8",
      "max-h-9",
      "max-h-10",
      "max-h-11",
      "max-h-12",
      "max-h-14",
      "max-h-16",
      "max-h-20",
      "max-h-24",
      "max-h-28",
      "max-h-32",
      "max-h-36",
      "max-h-40",
      "max-h-44",
      "max-h-48",
      "max-h-52",
      "max-h-56",
      "max-h-60",
      "max-h-64",
      "max-h-72",
      "max-h-80",
      "max-h-96",
      "max-h-full",
      "max-h-screen",
      "max-h-min",
      "max-h-max",
      "max-h-fit",
    ],
  },
];

export const altro = [
  { id: 1, name: "qualcosa1", values: ["empty"] },
  { id: 2, name: "qualcosa2", values: ["empty"] },
  { id: 3, name: "qualcosa3", values: ["empty"] },
  { id: 4, name: "qualcosa4", values: ["empty"] },
];
